### ISSUE TITLE
Value for points_for_plane

### ISSUE THREAD

**Issue by Beniko95J** [EnVision-Research/Ref-NeuS#10]
Hi, I am trying to use the provided function `evaluation_shinyblender` to evaluate the extracted mesh. The default value of parameter `points_for_plane`  in this function is `None`, but it seems to be necessary to set something for this parameter. Could you please what should I set for this parameter?

Thanks!

**Comment by g3956** [comment]
Hi, thanks for your interest in our work. 
The parameter `points_for_plane` is used to specify a plane. Only the points above the plane will be considered when computing the metric. Since the multi-view images in ShinyBlender do not show the bottom part. 
I manually assign these parameters for each object. You can download the file [Here](https://drive.google.com/file/d/1HGTD3uQUr8WrzRYZBagrg75_rQJmAK6S/view?usp=sharing).
