### ISSUE TITLE
GT dense point cloud

### ISSUE THREAD

**Issue by G-1nOnly** [EnVision-Research/Ref-NeuS#8]
Thanks for the wonderful work. I'm wondering how I could get the ground truth points_of_interet.ply, test_info.json and dense_pcd.ply for my own blender dataset?

**Comment by G-1nOnly** [comment]
For now, directly extracting PLY from blender seems to have an error "ValueError: PLY is unexpected length!". However, if I first extract OBJ from blender and then use meshlab to convert the OBJ to PLY format seems to work. If it's possible, I want to know the way you obtain the PLY file.

**Comment by g3956** [comment]
For `points_of_interet.ply`, you can export mesh with scale 1 from Blender (export stl or obj format and then transform to ply format in Meshlab).
For `test_info.json`, since parts of the object is unseen in multi-view images such as the bottom, I set a mask plane or bbox. The information is obtained manually from Meshlab.
For `dense_pcd.ply`, it is the same to `points_of_interet.ply` with larger scale. And you can upsample points in the mesh to obtain dense point cloud for evaluation.

**Comment by G-1nOnly** [comment]
Thank you for the quick response, so from my understanding, the dense_pcd.ply is also obtained from blender.
